/*
Vehicle Enquiry API

Interface specification for the DVLA Vehicle Enquiry API

API version: 1.2.0
Contact: DvlaAPIAccess@dvla.gov.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ves

import (
	"encoding/json"
)

// VehicleRequest struct for VehicleRequest
type VehicleRequest struct {
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
}

// NewVehicleRequest instantiates a new VehicleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleRequest() *VehicleRequest {
	this := VehicleRequest{}
	return &this
}

// NewVehicleRequestWithDefaults instantiates a new VehicleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleRequestWithDefaults() *VehicleRequest {
	this := VehicleRequest{}
	return &this
}

// GetRegistrationNumber returns the RegistrationNumber field value if set, zero value otherwise.
func (o *VehicleRequest) GetRegistrationNumber() string {
	if o == nil || o.RegistrationNumber == nil {
		var ret string
		return ret
	}
	return *o.RegistrationNumber
}

// GetRegistrationNumberOk returns a tuple with the RegistrationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleRequest) GetRegistrationNumberOk() (*string, bool) {
	if o == nil || o.RegistrationNumber == nil {
		return nil, false
	}
	return o.RegistrationNumber, true
}

// HasRegistrationNumber returns a boolean if a field has been set.
func (o *VehicleRequest) HasRegistrationNumber() bool {
	if o != nil && o.RegistrationNumber != nil {
		return true
	}

	return false
}

// SetRegistrationNumber gets a reference to the given string and assigns it to the RegistrationNumber field.
func (o *VehicleRequest) SetRegistrationNumber(v string) {
	o.RegistrationNumber = &v
}

func (o VehicleRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RegistrationNumber != nil {
		toSerialize["registrationNumber"] = o.RegistrationNumber
	}
	return json.Marshal(toSerialize)
}

type NullableVehicleRequest struct {
	value *VehicleRequest
	isSet bool
}

func (v NullableVehicleRequest) Get() *VehicleRequest {
	return v.value
}

func (v *NullableVehicleRequest) Set(val *VehicleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleRequest(val *VehicleRequest) *NullableVehicleRequest {
	return &NullableVehicleRequest{value: val, isSet: true}
}

func (v NullableVehicleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


